config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :directors do
    resources :movies
  end
  root :to => 'directors#index'

end

app/models/director.rb
class Director < ActiveRecord::Base
  
	has_many :movie, dependent: :destroy
  validates :movie, presence: true

end

app/models/movie.rb
class Movie < ActiveRecord::Base
	belongs_to :directors
	validates :title, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/directors_controller.rb
class DirectorsController < ApplicationController
	#before_filter :authenticate_user!
  

  def index
    @directors = Director.all
  end

  def create
    @director = Director.create(director_params)
    redirect_to directors_path
  end
  

  def update
    @director = Director.find params[:id]
    @director.update_attributes!(director_params)
    redirect_to director_path(@director)
  end

  def edit
    @director = Director.find params[:id]
  end
  def show
    id = params[:id]
    @director = Director.find(id)
  end
  private
  def director_params
      params.require(:director).permit(:name)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
	#before_filter :authenticate_user!
  def new
    @director = Director.find(params[:director_id])
    @movie = @director.movies.build
  end
  
  def show
    
  end

  def edit
    @movie = Movie.find(params[:id])
  end

  def index
    @director = Director.find(params[:director_id])
    @movies = Movie.where(director_id: params[:director_id])
  end
  
  def update
    @movie = Movie.find params[:id]
    @movie.update_attributes!(movie_params)
    director = @movie.director
    redirect_to director_movies_path(director)
  end

  def create
     @director = Director.find(params[:director_id])
     @movie = @director.movies.create(movie_params)
     redirect_to director_movies_path
  end
  private 
  def movie_params
    params.require(:movie).permit(:title, :rating, :releasedyear)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/directors_helper.rb
module DirectorsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/directors/edit.html.haml
%h1 Directors#edit
%h2 Edit Director information
%p Find me in app/views/directors/edit.html.haml
= form_tag director_path(@director), :method => :put do
  = label :director, :name, 'Name'
  = text_field :director, :name
  = submit_tag 'Save changes'

app/views/directors/index.html.haml
%h1 All Directors
%p Find me in app/views/directors/index.html.haml
%table#directors
  %thead
    %tr
      %th Name
      %th 
      %th movies
    %tbody
      - @directors.each do |d|
        %tr
          %td= d.name
          %td= link_to "Edit #{d.name}",director_path(d)
          %td= link_to "View movies", director_movies_path(d)
=link_to 'Add new director', new_director_path

app/views/directors/new.html.haml
%h1 Directors#new
%p Find me in app/views/directors/new.html.haml
%h2 Create a new Director
= form_tag directors_path, :method => :post do
  = label :director, :name, 'Name'
  = text_field :director, :name
  = submit_tag 'Save changes'

app/views/directors/show.html.haml
%h2 Details about #{@director.name}
%ul#details
  %li
=link_to 'Edit director information', edit_director_path(@director)
=link_to 'Back to directors list', directors_path

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Zurb Foundation %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div data-alert class="alert-box round <%= name.to_s == 'notice' ? 'success' : 'alert' %>">
      <%= content_tag :div, msg %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Zurb Foundation 5 %>
<nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name"><%= link_to 'Home', root_path %></li>
    <li class="toggle-topbar menu-icon"><a href="#">Menu</a></li>
  </ul>
  <div class="top-bar-section">
    <ul>
      <%= render 'layouts/navigation_links' %>
    </ul>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Project7" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Project7" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%# Modernizr is required for Zurb Foundation %>
    <%= javascript_include_tag 'vendor/modernizr' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
      <p class="navbar-text pull-right">
              <% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/movies/create.html.haml
<h1>Movies#create</h1>
<p>Find me in app/views/movies/create.html.erb</p>

app/views/movies/edit.html.haml
%h1 movies#edit
%p Find me in app/views/movies/edit.html.haml
%h2 Editing movie
= form_tag director_movie_path(movie_id: @movie.id), :method => :put do
  = label :movie, :title, 'Title'
  = string :movie, :title
  = label :movie , :rating, 'Rating' 
  = string :movie, :rating
  = label :movie, :releasedyear, 'Released Year'
  = string :movie, :releasedyear
  = submit_tag 'Save changes'

app/views/movies/index.html.haml
%h1 movies#index
%p 
="Movies from " + @director.name + " director" 
%table#movies
  %thead
    %tr
      %th Title
      %th Rating
      %th Released Year
    %tbody
      - @movies.each do |movie|
        %tr
          %td= movie.title
          %td= movie.rating
          %td= movie.title
          %td= link_to "Edit movie information", edit_director_movie_path(movie.director, movie)
=link_to 'Add new movie', new_director_movie_path(@director)

app/views/movies/new.html.haml
%h1 movies#new
%p 
="Adding a new movie to " + @director.name + " director" 
%h2 Create a new movie
= form_tag director_movies_path(@director), :method => :post do
  = label :movie, :title, 'Title'
  = string :movie, :title
  = label :movie , :rating, 'Rating' 
  = string :movie, :rating
  = label :movie, :releasedyear, 'Released Year'
  = string :movie, :releasedyear
  = submit_tag 'Save changes'

app/views/movies/show.html.haml
<h1>Movies#show</h1>
<p>Find me in app/views/movies/show.html.erb</p>

app/views/movies/update.html.haml
<h1>Moviees#update</h1>
<p>Find me in app/views/movies/update.html.erb</p>